<a href="https://colab.research.google.com/github/yesung05/2024-intro-DA-code/blob/main/w04_4_nparray_calculate.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

배열 연산


In [1]:
import numpy as np

a = np.arange(3)
a    

array([0, 1, 2])

In [2]:
print(a+2) #모든 값에 2씩 더하기
print(a-2) #모든 값에 2씩 빼기
print(a*2) #모든 값을 2로 곱하기
print(a/2) #모든 값을 2로 나누기

[2 3 4]
[-2 -1  0]
[0 2 4]
[0.  0.5 1. ]


In [3]:
a = np.arange(1,7).reshape(2,3)
a

array([[1, 2, 3],
       [4, 5, 6]])

In [4]:
b = np.full_like(a,[1,2,3]) #

In [5]:
print(a+b) 
print(a-b)
print(a*b)
print(a/b)

[[2 4 6]
 [5 7 9]]
[[0 0 0]
 [3 3 3]]
[[ 1  4  9]
 [ 4 10 18]]
[[1.  1.  1. ]
 [4.  2.5 2. ]]


In [6]:
a= np.arange(4)
a

array([0, 1, 2, 3])

In [7]:
b = np.arange(0.5, 4, 1)
b

array([0.5, 1.5, 2.5, 3.5])

In [8]:
a += b 

UFuncTypeError: Cannot cast ufunc 'add' output from dtype('float64') to dtype('int64') with casting rule 'same_kind'

In [9]:
b+=a 
b

array([0.5, 2.5, 4.5, 6.5])

In [10]:
a = np.full((2,3),[1,2,3])
a 

array([[1, 2, 3],
       [1, 2, 3]])

In [11]:
b = np.full((3,2),[2,1])
b

array([[2, 1],
       [2, 1],
       [2, 1]])

In [12]:
a @ b

array([[12,  6],
       [12,  6]])

In [13]:
a.dot(b) 

array([[12,  6],
       [12,  6]])

In [14]:
b.dot(a) 

array([[3, 6, 9],
       [3, 6, 9],
       [3, 6, 9]])

In [15]:
a = np.array([[10,20],[5,6],[1,2]]) 
a

array([[10, 20],
       [ 5,  6],
       [ 1,  2]])

In [16]:
a.sum()

np.int64(44)

In [17]:
a.sum(axis=0) 

array([16, 28])

In [18]:
a.sum(axis=1)

array([30, 11,  3])

In [19]:
import numpy as np

print(np.sum(a))
print(np.sum(a, axis=0))
print(np.sum(a, axis=1))

44
[16 28]
[30 11  3]


In [20]:
a = np.array([[3,5,7],[1,2,3]])
a

array([[3, 5, 7],
       [1, 2, 3]])

In [21]:
a.cumsum() 

array([ 3,  8, 15, 16, 18, 21])

In [22]:
a.cumsum(axis=0)

array([[ 3,  5,  7],
       [ 4,  7, 10]])

In [23]:
a.cumsum(axis=1)

array([[ 3,  8, 15],
       [ 1,  3,  6]])

In [24]:
import numpy as np
a = np.array([1,4,9])
np.sqrt(a) 

array([1., 2., 3.])

In [25]:
np.log(a)

array([0.        , 1.38629436, 2.19722458])

In [26]:
import numpy as np

a = np.array([1,4,9])
a

array([1, 4, 9])

In [27]:
b = np.full_like(a,2)
b

array([2, 2, 2])

In [28]:
np.add(a,b)

array([ 3,  6, 11])

In [29]:
np.divide(a,b)

array([0.5, 2. , 4.5])

In [30]:
np.power(a,b)

array([ 1, 16, 81])