<a href="https://colab.research.google.com/github/yesung05/2024-intro-DA-code/blob/main/w04_5_python_nparray_slicing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

배열 슬라이싱과 형태 수정


In [1]:
import numpy as np

a = np.power(np.arange(10),2) # 2 제곱씩
a

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [2]:
print(a[3])
print(a[-2]) 

9
64


In [3]:
print(a[1:4]) 
print(a[-5:-1]) 

[1 4 9]
[25 36 49 64]


In [4]:
print(a[8:2:-1]) 
print(a[-1:-7:-1])

[64 49 36 25 16  9]
[81 64 49 36 25 16]


In [5]:
a[::-1]

array([81, 64, 49, 36, 25, 16,  9,  4,  1,  0])

In [6]:
a[::-2] 

array([81, 49, 25,  9,  1])

In [7]:
a[2:5] = -100
a 

array([   0,    1, -100, -100, -100,   25,   36,   49,   64,   81])

In [8]:
a[2:5] =  [-5,-5,-5]
a

array([ 0,  1, -5, -5, -5, 25, 36, 49, 64, 81])

In [9]:
a[2:5] = [-5,-5] 

ValueError: could not broadcast input array from shape (2,) into shape (3,)

In [10]:
b = np.array([5]*10)
b


array([5, 5, 5, 5, 5, 5, 5, 5, 5, 5])

In [11]:
b[::2] = -10 
b

array([-10,   5, -10,   5, -10,   5, -10,   5, -10,   5])

In [12]:
b[::2] = np.arange(5) 
b

array([0, 5, 1, 5, 2, 5, 3, 5, 4, 5])

In [13]:
a = np.arange(30).reshape(5,6) 
a

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [14]:
a[3]

array([18, 19, 20, 21, 22, 23])

In [15]:
a[-1]

array([24, 25, 26, 27, 28, 29])

In [16]:
a[-2,:] 

array([18, 19, 20, 21, 22, 23])

In [17]:
a[2:4] 

array([[12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [18]:
a[1:5:2]

array([[ 6,  7,  8,  9, 10, 11],
       [18, 19, 20, 21, 22, 23]])

In [19]:
a[:,1] 

array([ 1,  7, 13, 19, 25])

In [20]:
a[:,1:6] 

array([[ 1,  2,  3,  4,  5],
       [ 7,  8,  9, 10, 11],
       [13, 14, 15, 16, 17],
       [19, 20, 21, 22, 23],
       [25, 26, 27, 28, 29]])

In [21]:
a[:,::2]

array([[ 0,  2,  4],
       [ 6,  8, 10],
       [12, 14, 16],
       [18, 20, 22],
       [24, 26, 28]])

In [22]:
a[2,4] 

np.int64(16)

In [23]:
a[2][4]

np.int64(16)

In [24]:
a[1:3,2:5]

array([[ 8,  9, 10],
       [14, 15, 16]])

In [25]:
a[:,:] 

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [26]:
a[::-1,::-1]

array([[29, 28, 27, 26, 25, 24],
       [23, 22, 21, 20, 19, 18],
       [17, 16, 15, 14, 13, 12],
       [11, 10,  9,  8,  7,  6],
       [ 5,  4,  3,  2,  1,  0]])

In [27]:
a = np.arange(24).reshape(2,3,4)
a


array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [28]:
a[1] 

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [29]:
a[:,1]

array([[ 4,  5,  6,  7],
       [16, 17, 18, 19]])

In [30]:
a[:, 1, 1]

array([ 5, 17])

In [31]:
a[...,1] 

array([[ 1,  5,  9],
       [13, 17, 21]])

In [32]:
a[1, ..., 1] 

array([13, 17, 21])

In [33]:
a[0,...]

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [34]:
a[0]

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [35]:
a = np.arange(12).reshape(2,3,2)
a

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]]])

In [36]:
a.ravel() 

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [37]:
a = np.arange(1,7).reshape(2,3)
a

array([[1, 2, 3],
       [4, 5, 6]])

In [38]:
np.transpose(a) 


array([[1, 4],
       [2, 5],
       [3, 6]])

In [39]:
a.transpose() 

array([[1, 4],
       [2, 5],
       [3, 6]])

In [40]:
a.T 

array([[1, 4],
       [2, 5],
       [3, 6]])

In [41]:
np.transpose(a,(0,1))

array([[1, 2, 3],
       [4, 5, 6]])

In [42]:
np.transpose(a,(1,0))

array([[1, 4],
       [2, 5],
       [3, 6]])

In [43]:
b = np.arange(1,13).reshape(3,2,2)
b

array([[[ 1,  2],
        [ 3,  4]],

       [[ 5,  6],
        [ 7,  8]],

       [[ 9, 10],
        [11, 12]]])

In [44]:
b.T

array([[[ 1,  5,  9],
        [ 3,  7, 11]],

       [[ 2,  6, 10],
        [ 4,  8, 12]]])

In [45]:
np.transpose(b,(0,1,2)) 

array([[[ 1,  2],
        [ 3,  4]],

       [[ 5,  6],
        [ 7,  8]],

       [[ 9, 10],
        [11, 12]]])

In [46]:
np. transpose(b,(2,1,0))

array([[[ 1,  5,  9],
        [ 3,  7, 11]],

       [[ 2,  6, 10],
        [ 4,  8, 12]]])

In [47]:
np.transpose(b,(0,2,1))

array([[[ 1,  3],
        [ 2,  4]],

       [[ 5,  7],
        [ 6,  8]],

       [[ 9, 11],
        [10, 12]]])

In [48]:
c = np.arange(1,13).reshape(2,2,3)
c

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [49]:
c.transpose(1,2,0)

array([[[ 1,  7],
        [ 2,  8],
        [ 3,  9]],

       [[ 4, 10],
        [ 5, 11],
        [ 6, 12]]])

In [50]:
np.transpose(c,(1,2,0))

array([[[ 1,  7],
        [ 2,  8],
        [ 3,  9]],

       [[ 4, 10],
        [ 5, 11],
        [ 6, 12]]])

In [51]:
np.transpose(c) 

array([[[ 1,  7],
        [ 4, 10]],

       [[ 2,  8],
        [ 5, 11]],

       [[ 3,  9],
        [ 6, 12]]])

In [52]:
x = np.array([[7,8,9]]) 
x

array([[7, 8, 9]])

In [53]:
y = np.swapaxes(x,0,1)
y

array([[7],
       [8],
       [9]])

In [54]:
y[0,0] = 10 
x

array([[10,  8,  9]])

In [55]:
x =  np.array(np.arange(8).reshape(2,2,2))
x

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [56]:
np.swapaxes(x,0,2) 

array([[[0, 4],
        [2, 6]],

       [[1, 5],
        [3, 7]]])

In [57]:
np.transpose(x,(2,1,0))

array([[[0, 4],
        [2, 6]],

       [[1, 5],
        [3, 7]]])

In [58]:
org = np.arange(5)
org

array([0, 1, 2, 3, 4])

In [59]:
v = org.view()
v

array([0, 1, 2, 3, 4])

In [60]:
v[2] = 200
v

array([  0,   1, 200,   3,   4])

In [61]:
org

array([  0,   1, 200,   3,   4])

In [62]:
org = np.arange(5)
org

array([0, 1, 2, 3, 4])

In [63]:
c = org.copy()
c

array([0, 1, 2, 3, 4])

In [64]:
c[2] = 200
c

array([  0,   1, 200,   3,   4])

In [65]:
org

array([0, 1, 2, 3, 4])

In [66]:
x = np.arange(6)
x

array([0, 1, 2, 3, 4, 5])

In [67]:
y = x.reshape(2,3)
y

array([[0, 1, 2],
       [3, 4, 5]])

In [68]:
y.base 

array([0, 1, 2, 3, 4, 5])

In [69]:
z = y.transpose()
z.base

array([0, 1, 2, 3, 4, 5])

In [70]:
c = z.copy()
print(c.base)

None


In [71]:
lst = list(range(8))
lst

[0, 1, 2, 3, 4, 5, 6, 7]

In [72]:
lst[3:5] = [30,40,50] 
lst

[0, 1, 2, 30, 40, 50, 5, 6, 7]

In [73]:
x = np.arange(8)
x

array([0, 1, 2, 3, 4, 5, 6, 7])

In [74]:
x[3:5] = [30,40] 
x

array([ 0,  1,  2, 30, 40,  5,  6,  7])

In [75]:
x[3:5] = [30,40,50]
x

ValueError: could not broadcast input array from shape (3,) into shape (2,)

In [76]:
a = np.array([[1,2,3],[4,5,6]])
a

array([[1, 2, 3],
       [4, 5, 6]])

In [77]:
b = a 
b is a

True

In [78]:
print(id(a))
print(id(b))

1548314926064
1548314926064


In [79]:
print(b.base)

None


In [80]:
b[0,0] = 100
a

array([[100,   2,   3],
       [  4,   5,   6]])

In [81]:
v = a.reshape(3,2)
v

array([[100,   2],
       [  3,   4],
       [  5,   6]])

In [82]:
print(id(a))
print(id(v))

1548314926064
1548314925008


In [83]:
v[0,1] = 200
a

array([[100, 200,   3],
       [  4,   5,   6]])

In [84]:
v.base

array([[100, 200,   3],
       [  4,   5,   6]])