<a href="https://colab.research.google.com/github/yesung05/2024-intro-DA-code/blob/main/w06_nparray_split.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

배열의 분리

기본함수  split() / np.split()                    

np.split(ary,n)

In [3]:
import numpy as np

x = np.arange(0,9)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [16]:
s = np.split(x,3)
s

[array([0, 1, 2]), array([3, 4, 5]), array([6, 7, 8])]

In [17]:
print(type(s))
print(s[0])

<class 'list'>
[0 1 2]


In [18]:
np.split(x,4) 

ValueError: array split does not result in an equal division

np.split(ary, [i,j,k,...])

In [19]:
x = np.arange(0,10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [20]:
np.split(x,[2,6])

[array([0, 1]), array([2, 3, 4, 5]), array([6, 7, 8, 9])]

In [21]:
y = np.arange(10,61,10)
y

array([10, 20, 30, 40, 50, 60])

In [22]:
np.split(y,[2,3,4])

[array([10, 20]), array([30]), array([40]), array([50, 60])]

In [23]:
np.split(y,[2,3,4,6])

[array([10, 20]),
 array([30]),
 array([40]),
 array([50, 60]),
 array([], dtype=int32)]

In [24]:
y[4:6]

array([50, 60])

In [25]:
y[6:]

array([], dtype=int32)

다차원 배열 np.hsplit(ary, n)

In [26]:
a = np.arange(24).reshape(2,12)
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23]])

In [27]:
np.split(a,3, axis = 1)

[array([[ 0,  1,  2,  3],
        [12, 13, 14, 15]]),
 array([[ 4,  5,  6,  7],
        [16, 17, 18, 19]]),
 array([[ 8,  9, 10, 11],
        [20, 21, 22, 23]])]

In [28]:
np.split(a,4, axis = 1)

[array([[ 0,  1,  2],
        [12, 13, 14]]),
 array([[ 3,  4,  5],
        [15, 16, 17]]),
 array([[ 6,  7,  8],
        [18, 19, 20]]),
 array([[ 9, 10, 11],
        [21, 22, 23]])]

In [29]:
np.split(a, 5, axis=1)

ValueError: array split does not result in an equal division

In [30]:
np.split(a,[3,5,7],axis=1)

[array([[ 0,  1,  2],
        [12, 13, 14]]),
 array([[ 3,  4],
        [15, 16]]),
 array([[ 5,  6],
        [17, 18]]),
 array([[ 7,  8,  9, 10, 11],
        [19, 20, 21, 22, 23]])]

In [31]:
b = np.arange(24).reshape(6,4)
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [32]:
np.split(b,3,axis=0)

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]]),
 array([[16, 17, 18, 19],
        [20, 21, 22, 23]])]

In [33]:
np.split(b,[2,4,6],axis=0)

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]]),
 array([[16, 17, 18, 19],
        [20, 21, 22, 23]]),
 array([], shape=(0, 4), dtype=int32)]

분할 함수 hsplit()과 split()
np.hsplit(ary)

In [34]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [35]:
np.hsplit(a,2)

[array([0, 1, 2, 3, 4]), array([5, 6, 7, 8, 9])]

In [36]:
np.hsplit(a,[2,5])

[array([0, 1]), array([2, 3, 4]), array([5, 6, 7, 8, 9])]

In [37]:
a = np.arange(24).reshape(2,12)
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23]])

In [38]:
np.hsplit(a,3) 

[array([[ 0,  1,  2,  3],
        [12, 13, 14, 15]]),
 array([[ 4,  5,  6,  7],
        [16, 17, 18, 19]]),
 array([[ 8,  9, 10, 11],
        [20, 21, 22, 23]])]

In [39]:
np.hsplit(a,4) 

[array([[ 0,  1,  2],
        [12, 13, 14]]),
 array([[ 3,  4,  5],
        [15, 16, 17]]),
 array([[ 6,  7,  8],
        [18, 19, 20]]),
 array([[ 9, 10, 11],
        [21, 22, 23]])]

In [40]:
np.hsplit(a,5) 

ValueError: array split does not result in an equal division

In [41]:
np.hsplit(a,(3,5,8)) 

[array([[ 0,  1,  2],
        [12, 13, 14]]),
 array([[ 3,  4],
        [15, 16]]),
 array([[ 5,  6,  7],
        [17, 18, 19]]),
 array([[ 8,  9, 10, 11],
        [20, 21, 22, 23]])]

In [42]:
a[:,:3]

array([[ 0,  1,  2],
       [12, 13, 14]])

In [43]:
a[:,8:]

array([[ 8,  9, 10, 11],
       [20, 21, 22, 23]])

np.vsplit(ary)

In [44]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [45]:
np.vsplit(2) 

TypeError: vsplit() missing 1 required positional argument: 'indices_or_sections'

In [46]:
a = np.arange(18).reshape(6,3)

In [47]:
np.vsplit(a,3)

[array([[0, 1, 2],
        [3, 4, 5]]),
 array([[ 6,  7,  8],
        [ 9, 10, 11]]),
 array([[12, 13, 14],
        [15, 16, 17]])]

In [48]:
np.vsplit(a,4) 

ValueError: array split does not result in an equal division

In [49]:
np.vsplit(a,(1,4,6)) 

[array([[0, 1, 2]]),
 array([[ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]]),
 array([[12, 13, 14],
        [15, 16, 17]]),
 array([], shape=(0, 3), dtype=int32)]

In [50]:
a[4:6,:]

array([[12, 13, 14],
       [15, 16, 17]])

In [51]:
a[6:, :] 

array([], shape=(0, 3), dtype=int32)